#!/usr/bin/python3

from sys import argv

def factorize(number_to_check):
    """Find two small numbers that multiply to give a given number."""
    i = 2

    if number_to_check < 2:
        return
    
    while number_to_check % i:
        i += 1
    print("{:.0f} = {:.0f} * {:.0f}".format(number_to_check, number_to_check / i, i))

def main():
    if len(argv) != 2:
        print("Usage: python script.py <filename>")
        exit()

    try:
        with open(argv[1]) as file:
            for line in file:
                number_to_check = int(line.strip())
                factorize(number_to_check)
    except FileNotFoundError:
        print(f"File '{argv[1]}' not found.")
    except ValueError:
        print("Invalid input in the file. Please provide valid integers.")

if __name__ == "__main__":
    main()

